# Generated by Django 4.1.1 on 2022-09-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaislabadJhungAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('VIA', models.CharField(blank=True, max_length=50, null=True)),
                ('Truck_Number', models.CharField(max_length=10)),
                ('Truck_Company', models.CharField(max_length=50)),
                ('Total_CTN', models.IntegerField()),
                ('To_Pay', models.IntegerField()),
                ('Truck_Rent', models.IntegerField()),
                ('Karachi_Transit_Rent', models.IntegerField(blank=True, null=True)),
                ('Lahore_Transit_Rent', models.IntegerField(blank=True, null=True)),
                ('FSD_to_Jhung_Transit_Rent', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Faislabad & Jhung Account',
                'verbose_name_plural': 'Faislabad & Jhung Account',
            },
        ),
        migrations.CreateModel(
            name='GujranwalaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('VIA', models.CharField(blank=True, max_length=50, null=True)),
                ('Truck_Number', models.CharField(max_length=10)),
                ('Truck_Company', models.CharField(max_length=50)),
                ('Total_CTN', models.IntegerField()),
                ('To_Pay', models.IntegerField()),
                ('Truck_Rent', models.IntegerField()),
                ('Karachi_Transit_Rent', models.IntegerField(blank=True, null=True)),
                ('Lahore_Transit_Rent', models.IntegerField(blank=True, null=True)),
                ('Rawalpindi_Transit_Rent', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Gujranwala Account',
                'verbose_name_plural': 'Gujranwala Account',
            },
        ),
        migrations.CreateModel(
            name='GujratAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('VIA', models.CharField(blank=True, max_length=50, null=True)),
                ('Truck_Number', models.CharField(max_length=10)),
                ('Truck_Company', models.CharField(max_length=50)),
                ('Total_CTN', models.IntegerField()),
                ('To_Pay', models.IntegerField()),
                ('Truck_Rent', models.IntegerField()),
                ('Karachi_Transit_Rent', models.IntegerField(blank=True, null=True)),
                ('Lahore_Transit_Rent', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Gujrat Account',
                'verbose_name_plural': 'Gujrat Account',
            },
        ),
        migrations.CreateModel(
            name='LahoreAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Truck_Number', models.CharField(max_length=10)),
                ('Truck_Company', models.CharField(max_length=50)),
                ('Total_CTN', models.IntegerField()),
                ('To_Pay', models.IntegerField()),
                ('Truck_Rent', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Lahore Account',
                'verbose_name_plural': 'Lahore Account',
            },
        ),
        migrations.CreateModel(
            name='MultanAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('VIA', models.CharField(blank=True, max_length=50, null=True)),
                ('Truck_Number', models.CharField(max_length=10)),
                ('Truck_Company', models.CharField(max_length=50)),
                ('Total_CTN', models.IntegerField()),
                ('To_Pay', models.IntegerField()),
                ('Truck_Rent', models.IntegerField()),
                ('Karachi_Transit_Rent', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Multan Account',
                'verbose_name_plural': 'Multan Account',
            },
        ),
        migrations.CreateModel(
            name='RawalpindiAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('VIA', models.CharField(blank=True, max_length=50, null=True)),
                ('Truck_Number', models.CharField(max_length=10)),
                ('Truck_Company', models.CharField(max_length=50)),
                ('Total_CTN', models.IntegerField()),
                ('To_Pay', models.IntegerField()),
                ('Truck_Rent', models.IntegerField()),
                ('Karachi_Transit_Rent', models.IntegerField(blank=True, null=True)),
                ('Lahore_Transit_Rent', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Rawalpindi Account',
                'verbose_name_plural': 'Rawalpindi Account',
            },
        ),
    ]
