# Generated by Django 4.1.1 on 2022-09-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amcCargoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faislabadjhungaccount',
            name='FSD_to_Jhung_Transit_Rent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='faislabadjhungaccount',
            name='Karachi_Transit_Rent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='faislabadjhungaccount',
            name='Lahore_Transit_Rent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='faislabadjhungaccount',
            name='To_Pay',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='faislabadjhungaccount',
            name='Total_CTN',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='faislabadjhungaccount',
            name='Truck_Rent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gujranwalaaccount',
            name='Karachi_Transit_Rent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gujranwalaaccount',
            name='Lahore_Transit_Rent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gujranwalaaccount',
            name='Rawalpindi_Transit_Rent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gujranwalaaccount',
            name='To_Pay',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gujranwalaaccount',
            name='Total_CTN',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gujranwalaaccount',
            name='Truck_Rent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gujrataccount',
            name='Karachi_Transit_Rent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gujrataccount',
            name='Lahore_Transit_Rent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gujrataccount',
            name='To_Pay',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gujrataccount',
            name='Total_CTN',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gujrataccount',
            name='Truck_Rent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lahoreaccount',
            name='To_Pay',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lahoreaccount',
            name='Total_CTN',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lahoreaccount',
            name='Truck_Rent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='multanaccount',
            name='Karachi_Transit_Rent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='multanaccount',
            name='To_Pay',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='multanaccount',
            name='Total_CTN',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='multanaccount',
            name='Truck_Rent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rawalpindiaccount',
            name='Karachi_Transit_Rent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rawalpindiaccount',
            name='Lahore_Transit_Rent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rawalpindiaccount',
            name='To_Pay',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rawalpindiaccount',
            name='Total_CTN',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rawalpindiaccount',
            name='Truck_Rent',
            field=models.IntegerField(default=0),
        ),
    ]
