# Generated by Django 4.1.1 on 2022-09-19 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amcCargoApp', '0002_alter_faislabadjhungaccount_fsd_to_jhung_transit_rent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LahoreWeeklyClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('Previous_Balance', models.IntegerField(default=0)),
                ('Current_to_Pay', models.IntegerField(default=0)),
                ('Recovery', models.IntegerField(default=0)),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amcCargoApp.lahoreaccount')),
            ],
        ),
    ]
