# Generated by Django 4.1.1 on 2022-09-19 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amcCargoApp', '0003_lahoreweeklyclosing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lahoreweeklyclosing',
            name='Account',
        ),
    ]
