# Generated by Django 4.1.1 on 2022-09-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amcCargoApp', '0004_remove_lahoreweeklyclosing_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='lahoreaccount',
            name='Delivery_Day',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lahoreaccount',
            name='Recovery_Amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
