# Generated by Django 4.1.1 on 2022-09-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amcCargoApp', '0006_rename_recovery_amount_lahoreaccount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faislabadjhungaccount',
            name='Amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='faislabadjhungaccount',
            name='Payment_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gujranwalaaccount',
            name='Amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gujranwalaaccount',
            name='Payment_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gujrataccount',
            name='Amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gujrataccount',
            name='Payment_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multanaccount',
            name='Amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='multanaccount',
            name='Payment_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawalpindiaccount',
            name='Amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='rawalpindiaccount',
            name='Payment_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
